language: python
python:
#  - "3.5"
#  - "3.6"
  - "3.7"
#  - "3.8"
jobs:
  include:
    - name: flake8
      env: TOXENV=flake8
      before_script:
      after_success:
  allow_failures:
    - python: 3.7
install:
  - pip install tox-travis coveralls
# command to run tests
script:
  - tox
# do not send emails of broken builds
notifications:
  email: false
after_script:
  - coveralls
cache:
  pip: true
